AWSTemplateFormatVersion: '2010-09-09'
Description: A CloudFormation template to create an S3 bucket and RDS MySQL instance.

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'jameer-cloudformation-s3bucket'

  MyRDSInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBName: mydatabasecloud
      AllocatedStorage: '20'
      DBInstanceClass: 'db.t3.micro'
      Engine: 'MySQL'
      MasterUsername: 'admin'
      MasterUserPassword: 'password123'
      BackupRetentionPeriod: 1
      PubliclyAccessible: true
